on:
  push:
    branches: [master]
  pull_request:

name: CI

jobs:
  run_testcode:
    name: Run zoker test code
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@master

      # Cache to speed up workflow
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      # Build Project
      - name: Build zoker code
        run: cargo build --verbose

      # Test Project
      - name: Run test Test Code
        run: cargo test --verbose --all

  check_format:
    name: Check Rust code with rustfmt and clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Format check
        run: cargo fmt -- --check
      - name: Run Clippy
        run: cargo clippy -- -Dwarnings
