name: Rust

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    # Cache to speed up workflow
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    # Build Project
    - name: Build
      run: cargo build --verbose
    
    # Test Project
    - name: Run test Format check
      run: cargo fmt -- --check
    - name: Run test Clippy
      run: cargo clippy -- -Dwarnings
    - name: Run test Test Code
      run: cargo test --verbose
